In [49]:
import numpy as np
print(np.__version__)

1.26.4


In [50]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [51]:
arr2 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

In [53]:
zeros_array = np.zeros(5)
zeros_int = zeros_array.astype(int)
print(zeros_int)

[0 0 0 0 0]


In [54]:
print(zeros_array.dtype)

float64


In [55]:
zeros_int.dtype

dtype('int32')

In [56]:
new_arr= np.array([[1,2,3,4],[4,5,6,5],[7,8,9,6]])
print(new_arr)

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 6]]


In [57]:
new_arr.dtype

dtype('int32')

In [58]:
new_arr.shape

(3, 4)

In [59]:
arr4=np.ones((3,4),dtype=int)
print(arr4)
print(type(arr4))
np.shape(arr4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
<class 'numpy.ndarray'>


(3, 4)

In [65]:
x =np.array([[1,2,3],[4,5,6],[6,7,8]])
np.swapaxes(x,0,1)

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [66]:
x.max()

8

In [67]:
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [6],
       [7],
       [8]])

In [74]:
y=np.array([[1,5,2],[4,9,67],[45,1,5]])
y.sort(axis=0)
y

array([[ 1,  1,  2],
       [ 4,  5,  5],
       [45,  9, 67]])

In [75]:
x=np.array([[1,5,2],[4,9,67],[45,1,5]])
x.sort(axis=1)
x

array([[ 1,  2,  5],
       [ 4,  9, 67],
       [ 1,  5, 45]])

In [81]:
x=np.linspace(6,1)
z= x.astype(int)
z

array([6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [84]:
arr7=np.ones((3,4),dtype=int)
print(arr7)
print(type(arr7))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
<class 'numpy.ndarray'>


In [85]:
arr4=np.zeros((3,4),dtype=int)
print(arr4)
print(type(arr4))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<class 'numpy.ndarray'>
